# Generated by Django 2.0.2 on 2018-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='create_time',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='blogtype',
            name='type_name',
            field=models.CharField(max_length=30),
        ),
    ]
